name: learn
on: pull_request: types: opened
jobs:
  get-pr-test:
    runs-on: ubuntu-latest
    steps:
      run:
        curl -X POST \
             -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -d "{\"body\": \"${{ github.event.pull_request.diff_url }}\"}" \
             ${{ github.event.pull_request.comments_url }}
